export const applianceDataset = [
  { name: 'LED Bulb (5W)', wattage: 5, category: 'Lighting' },
  { name: 'LED Bulb (10W)', wattage: 10, category: 'Lighting' },
  { name: 'Energy Saving Bulb (20W)', wattage: 20, category: 'Lighting' },
  { name: 'Ceiling Fan', wattage: 75, category: 'Cooling' },
  { name: 'Standing Fan', wattage: 50, category: 'Cooling' },
  { name: 'LCD/LED TV (32")', wattage: 60, category: 'Entertainment' },
  { name: 'LCD/LED TV (55")', wattage: 120, category: 'Entertainment' },
  { name: 'Home Theater System', wattage: 100, category: 'Entertainment' },
  { name: 'Gaming Console', wattage: 150, category: 'Entertainment' },
  { name: 'Small Fridge (Single Door)', wattage: 150, category: 'Kitchen' },
  { name: 'Large Fridge (Double Door)', wattage: 300, category: 'Kitchen' },
  { name: 'Deep Freezer (Small)', wattage: 200, category: 'Kitchen' },
  { name: 'Deep Freezer (Large)', wattage: 400, category: 'Kitchen' },
  { name: 'Microwave Oven', wattage: 1200, category: 'Kitchen' },
  { name: 'Electric Kettle', wattage: 2000, category: 'Kitchen' },
  { name: 'Toaster', wattage: 800, category: 'Kitchen' },
  { name: 'Air Conditioner (1.0 HP)', wattage: 900, category: 'Cooling', surgeFactor: 3 },
  { name: 'Air Conditioner (1.5 HP)', wattage: 1350, category: 'Cooling', surgeFactor: 3 },
  { name: 'Air Conditioner (2.0 HP)', wattage: 1800, category: 'Cooling', surgeFactor: 3 },
  { name: 'Inverter AC (1.0 HP)', wattage: 600, category: 'Cooling', surgeFactor: 1.5 },
  { name: 'Inverter AC (1.5 HP)', wattage: 900, category: 'Cooling', surgeFactor: 1.5 },
  { name: 'Laptop Computer', wattage: 65, category: 'Office' },
  { name: 'Desktop Computer', wattage: 250, category: 'Office' },
  { name: 'Laser Printer', wattage: 500, category: 'Office' },
  { name: 'Water Pump (0.5 HP)', wattage: 375, category: 'Utility', surgeFactor: 3 },
  { name: 'Water Pump (1.0 HP)', wattage: 750, category: 'Utility', surgeFactor: 3 },
  { name: 'Washing Machine', wattage: 500, category: 'Utility' },
  { name: 'Electric Iron', wattage: 1500, category: 'Utility' },
  { name: 'Hair Dryer', wattage: 1200, category: 'Utility' }
];
